'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toast } from '@/components/ui/shadcn/toast';
import './globals.css';
import { Providers } from '@/app/provider';
import { Navbar } from '@/components/Navigation/Navbar/Navbar';
import Sidebar from '@/components/Navigation/Sidebar/Sidebar';
import { Toaster } from 'sonner';
const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en' className='scroll-smooth'>
			<head>
				<title>Sechaba Care</title>
				<meta
					name='description'
					content='Botswana Health Care Medication Management System'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1, maximum-scale=1'
				/>
				<meta name='apple-mobile-web-app-capable' content='yes' />
				<meta name='apple-mobile-web-app-status-bar-style' content='green' />
			</head>
			<body>
				<Providers>
					{
						<>
							<Navbar />
							{/* <Sidebar/> */}
							{children}
							<Toaster />
						</>
					}
				</Providers>
			</body>
		</html>
	);
}
